INTRODUCTION TO NUMPY

In [3]:
import numpy as np

In [4]:
x=np.array([23,45,1])
y=np.array([2,34,1])
w=(x*y)

In [5]:
newArray=x,w
print(newArray)

(array([23, 45,  1]), array([  46, 1530,    1]))


In [6]:
#get dimension
x.ndim
y.ndim
w.ndim

1

In [7]:
dennis=np.array([[23,45,67,8,67,3],[12,3,4,6,3,8],[45,7,34,90,67,3]])
dennis2=np.array([[23,45,67,8,67,3],[12,3,4,6,3,8],[45,7,34,90,67,3]],dtype='int16')
print (dennis)

[[23 45 67  8 67  3]
 [12  3  4  6  3  8]
 [45  7 34 90 67  3]]


In [8]:
#get shape
#get type
#get itemsize
print(dennis.shape)
print(dennis.dtype)
print(dennis2.dtype)
print(dennis.itemsize)
print(dennis2.itemsize)

(3, 6)
int32
int16
4
2


In [9]:
#get specific element[r,c]
print(dennis[0,0])
print(dennis[2,5])
print(dennis[1,3])
print(dennis[:,2])

23
3
6
[67  4 34]


In [10]:
#more (startIndx,endIndx,stepsize)
print(dennis)
print(dennis[2,0:5:2])
print(dennis[2,0:-5:2])

[[23 45 67  8 67  3]
 [12  3  4  6  3  8]
 [45  7 34 90 67  3]]
[45 34 67]
[45]


In [11]:
#adding more values to arrays
dennis

array([[23, 45, 67,  8, 67,  3],
       [12,  3,  4,  6,  3,  8],
       [45,  7, 34, 90, 67,  3]])

In [12]:
dennis[2,0:-2]=[30,20,40,50]
print(dennis)
dennis[1,2]=99
print(dennis)
dennis[0,-3]=100
print(dennis)

[[23 45 67  8 67  3]
 [12  3  4  6  3  8]
 [30 20 40 50 67  3]]
[[23 45 67  8 67  3]
 [12  3 99  6  3  8]
 [30 20 40 50 67  3]]
[[ 23  45  67 100  67   3]
 [ 12   3  99   6   3   8]
 [ 30  20  40  50  67   3]]


In [13]:
dennis

array([[ 23,  45,  67, 100,  67,   3],
       [ 12,   3,  99,   6,   3,   8],
       [ 30,  20,  40,  50,  67,   3]])

In [14]:
dennis2=np.array([[[34,55],[45,89]],[[34,76],[21,90]]])
print(dennis2)

[[[34 55]
  [45 89]]

 [[34 76]
  [21 90]]]


In [15]:
#get a specific element which is outside another blocka array
print(dennis2[1,1,1])
print(dennis2[0,0,1])
print(dennis2[0,:,0])
print(dennis2[1,1:])
print(dennis2[1,:,1])
print(dennis2[1,:,1])
dennis2[1,:]=[[30,50],[70,43]]
print(dennis2)

90
55
[34 45]
[[21 90]]
[76 90]
[76 90]
[[[34 55]
  [45 89]]

 [[30 50]
  [70 43]]]


In [16]:
#all zeros matrix
dennis3=np.zeros((2,3,5))
dennis4=np.full_like(dennis3,45)
print(dennis4)
print(dennis3)

[[[45. 45. 45. 45. 45.]
  [45. 45. 45. 45. 45.]
  [45. 45. 45. 45. 45.]]

 [[45. 45. 45. 45. 45.]
  [45. 45. 45. 45. 45.]
  [45. 45. 45. 45. 45.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [17]:
#random decimal numbers
dennis5=np.random.rand(4,2)
print(dennis5)
dennis6=np.random.sample(dennis3.shape)
print(dennis6)

[[0.89546298 0.37785433]
 [0.37232882 0.052388  ]
 [0.28562571 0.33299888]
 [0.30529526 0.14360672]]
[[[0.25538491 0.41415107 0.65963245 0.47796563 0.88780219]
  [0.20526053 0.43593478 0.01689214 0.52181488 0.33890923]
  [0.77528429 0.80791983 0.69949246 0.03025926 0.03062059]]

 [[0.13585393 0.13992954 0.0791908  0.8996961  0.9413114 ]
  [0.96299484 0.59245258 0.92899231 0.36045619 0.80396558]
  [0.13928315 0.05596539 0.72917591 0.996448   0.32499625]]]


In [18]:
#random intergers
np.random.randint(50,100,size=(4,4))

array([[83, 61, 52, 73],
       [87, 51, 70, 72],
       [78, 80, 92, 82],
       [97, 73, 90, 78]])

In [19]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#repeat matrix array
dennis7=np.array([[34,44,54,64]])
dennis8=np.repeat(dennis7,4,axis=0)
print(dennis8)




[[34 44 54 64]
 [34 44 54 64]
 [34 44 54 64]
 [34 44 54 64]]


In [21]:
dennis8=np.ones((5,5))
print(dennis8)
dennis9=np.zeros((3,3))
print(dennis9)
dennis9[1,1]=9
print(dennis9)
dennis8[1:4,1:4]=dennis9
print(dennis8)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
#mathematics
arra=np.array([3,4,16,8])
print(arra*3)
d1=round((arra/3),1)
print(arra-2)

[ 9 12 48 24]


TypeError: type numpy.ndarray doesn't define __round__ method

In [42]:
#the number of colums in x should be equal to number of rows in y
x=np.ones([4,3])
print(x)
y=np.full((3,2), 2)
print(y)
print(np.matmul(x,y))


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]]


In [50]:
#find the determinant
c=np.identity(4)
print(c)
d=np.linalg.det(c)
print("Determinant of an identity matrix is : ",d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Determinant of an identity matrix is :  1.0


In [67]:
#Statistics
#for axis 1 it will look for the min/sum/max value horizontal
#for axis 0 it will look for the min value vertically
der=np.array([[34,78,56],[23,78,87],[34,45,12]])
print(der)
print("*"*12)
print(np.min(der,axis=1))
print("*"*12)
print(np.max(der,axis=1))
print("*"*12)
print(np.sum(der,axis=1))
print("*"*12)
print(np.min(der,axis=0))
print("*"*12)
print(np.max(der,axis=0))
print("*"*12)
print(np.sum(der,axis=0))

[[34 78 56]
 [23 78 87]
 [34 45 12]]
************
[34 23 12]
************
[78 87 45]
************
[168 188  91]
************
[23 45 12]
************
[34 78 87]
************
[ 91 201 155]


In [72]:
#Reorganizing Arrays
before=np.array([[23,45,67,8,67,3],[12,3,4,6,3,8],[45,7,34,90,67,3]])
print(before)
after=before.reshape(3,6)
print(after)

[[23 45 67  8 67  3]
 [12  3  4  6  3  8]
 [45  7 34 90 67  3]]
[[23 45 67  8 67  3]
 [12  3  4  6  3  8]
 [45  7 34 90 67  3]]


In [73]:
#verticall stacking
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.vstack([x,y,x,y]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [81]:
#load data from files
filedata=np.genfromtxt('data.txt', delimiter=",")
print(filedata)
print("*"*42)
filedata=filedata.astype("int32")
print(filedata)


[23. 34.  5.  6.  7.  8.  8.  9. 34. 67. 67. 45. 23. 45. 22. 34. 77. 90.
 56. 78.  7. 56. 68. 34. 56. 12. 32. 43. 67. 78. 58. 25. 28. 37. 35. 49.
 46. 68.  6. 45.]
******************************************
[23 34  5  6  7  8  8  9 34 67 67 45 23 45 22 34 77 90 56 78  7 56 68 34
 56 12 32 43 67 78 58 25 28 37 35 49 46 68  6 45]


In [83]:
#boolean masking and advanced indexing
print(filedata>50)
print(filedata[filedata>50])

[False False False False False False False False False  True  True False
 False False False False  True  True  True  True False  True  True False
  True False False False  True  True  True False False False False False
 False  True False False]
[67 67 77 90 56 78 56 68 56 67 78 58 68]


In [85]:
dert=np.array([1,6,8,9,5,3])
dert[[1,2,5]]

array([6, 8, 3])

In [95]:
np.all(filedata > 50, axis=0)

False

In [88]:
filedata

array([23, 34,  5,  6,  7,  8,  8,  9, 34, 67, 67, 45, 23, 45, 22, 34, 77,
       90, 56, 78,  7, 56, 68, 34, 56, 12, 32, 43, 67, 78, 58, 25, 28, 37,
       35, 49, 46, 68,  6, 45])

In [98]:
dert1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
dert1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [100]:
dert1[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [104]:
dert1[[1,2,3,4],[1,2,3,4]]

array([ 7, 13, 19, 25])

In [105]:
dert1[4:6,3:5]

array([[24, 25],
       [29, 30]])